name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-staging-repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository-id: ${{ steps.create.outputs.repository-id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@v1
        with:
          username: andreypfau
          password: ${{ secrets.OSSRH_PASSWORD }}
          staging-profile-id: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          description: Created by GitHub Actions
  metadata-publish:
    name: Publish Metadata
    runs-on: ubuntu-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Additional setup here
      - name: Publish Metadata
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dmetadata_only
  linux-publish:
    name: Publish on Linux
    runs-on: ubuntu-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Additional setup here
      - name: Publish
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dsplit_targets
  macos-publish:
    name: Publish on macOS
    runs-on: macos-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Additional setup here
      - name: Publish
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dsplit_targets
  windows-publish:
    name: Publish on Windows
    runs-on: windows-latest
    needs: create-staging-repository
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Additional setup here
      - name: Publish
        env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create-staging-repository.outputs.repository-id }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish -Dsplit_targets
  close-staging-repository:
    name: Close staging repository
    runs-on: ubuntu-latest
    needs: [ create-staging-repository, metadata-publish, linux-publish, macos-publish ]
    steps:
      - name: Close staging repository
        uses: nexus-actions/release-nexus-staging-repo@main
        with:
          username: andreypfau
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.create-staging-repository.outputs.repository-id }}
          close_only: 'true'
